---
title: "Master of Urbanism - Q3 - GIS Workshop"
format: html
---

## 👩‍🏫👨‍🏫🎓Instructors

-   Claudiu Forgaci

-   Birgit Hausleitner

-   Daniele Cannatella

## Dates and Deadlines

**Week 2 - Wednesday, 18 February**

(Flux Hall A)

**08:45 \| Media analysis**

(Self-study)

**13:45 \| Spatial analysis toward typology construction**

**18:00 \| SUBMIT ASSIGNMENT**

**Week 3 - Monday, 23 February**

(ARCH-Lecture Hall B. 08.BG.Oost.370) 

**11:00 \| GIS Q&A session**

**Week 3 - Wednesday, 25 February**

(TPM Hall A) 

**08:45 \| Media Analysis**

**Week 4 - Wednesday, 4 March**

(AS-Franklin Hall and Waterman (58.A2.050/58.A2.110))

**08:45 \| Typology construction with cluster analysis**

## Resources

### Data Download

Click [here](https://surfdrive.surf.nl/s/GmbX2FRKjixAaLa) to download the dataset.

### Software

-   QGIS 3.40 LTR

-   [GeoDa](https://geodacenter.github.io/download)

### Assignments and Instructions

#### **Get the GIS data from [https://surfdrive.suxrf.nl/s/GmbX2FRKjixAaLa](https://surfdrive.surf.nl/s/GmbX2FRKjixAaLa)**

**Follow these tutorials:**

[**Creating a 2x2km Fishnet Grid**](https://sdgis-edu-tud.github.io/pages/learn-qgis/spatial-data-preparation/creating-fishnet.html)or use the one created by us in the dataset

1.  [**Mapping Photovoltaic Potential Across Dutch Municipalities**](https://sdgis-edu-tud.github.io/pages/learn-qgis/environmental-assessment/pv-potential.html)

2.  [**CLC to grid**](https://sdgis-edu-tud.github.io/pages/learn-qgis/misc/land-use-grid-aggregation.html)

3.  [**Road Density Analysis**](https://sdgis-edu-tud.github.io/pages/learn-qgis/density-analysis/road-network-density.html)

4.  **Add one more analysis relevant for your group (we recommend you apply the workflow of Tutorial 1 on use the gas supply per home data on postcode level included in the dataset)**

::: callout-important
**IMPORTANT: the results of all analyses should be saved on the grid. Run the analysis in sequence and store the results in the same attribute table. This is needed for the workshop in Week 4.**
:::

**Go to Miro: <https://miro.com/app/board/uXjVGCONmLk=/> Password: q3gis2026**

-   **Ask questions before 17 February, 18:00**

-   **Submit assignment before 18 February, 18:00**

**You will carry out the assignments in your studio groups, which will be formed on Friday 13 February**

### Tutorials and Resources

-   [**Creating a 2x2km Fishnet Grid**](/pages/learn-qgis/spatial-data-preparation/creating-fishnet.qmd)
-   [**Mapping Photovoltaic Potential Across Dutch Municipalities**](/pages/learn-qgis/environmental-assessment/pv-potential.qmd)
-   [**CLC to grid**](/pages/learn-qgis/misc/land-use-grid-aggregation.qmd)
-   [**Road Density Analysis**](/pages/learn-qgis/density-analysis/road-network-density.qmd)
